version: '3'
services:
  dashboard:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
